"""Tests for libexec/azurevpn-helper argument and config validation.

Pure Python, no root, no VPN: everything runs against temp directories.
"""
import importlib.machinery
import importlib.util
import os
import stat
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load(name, rel):
    loader = importlib.machinery.SourceFileLoader(name, str(ROOT / rel))
    spec = importlib.util.spec_from_loader(name, loader)
    mod = importlib.util.module_from_spec(spec)
    loader.exec_module(mod)
    return mod


helper = load("azurevpn_helper", "libexec/azurevpn-helper")
shim = load("azurevpn_sudo", "libexec/azurevpn-sudo")

UID = 4242
SOCK = f"/run/user/{UID}/openp2s/mgmt.sock"
KEY = "-----BEGIN OpenVPN Static key V1-----\n0123456789abcdef0123456789abcdef\n-----END OpenVPN Static key V1-----"


def good_config(**over):
    """Config in the shape openp2s 0.2.0 generates (management credentials)."""
    parts = {
        "head": "# Generated by OpenP2S. Do not edit\nclient\ndev tun\nproto tcp-client\n\n"
                "remote gw.example.invalid 443\nnobind\nresolv-retry infinite\nremote-cert-tls server\n"
                "verify-x509-name *.vpn.example.invalid name\ncipher AES-256-GCM\n"
                "data-ciphers AES-256-GCM\ndata-ciphers-fallback AES-256-GCM\nauth SHA256\n"
                "reneg-sec 0\nauth-nocache\nca /etc/ssl/certs/ca-certificates.crt\n",
        "mgmt": f"auth-user-pass\nmanagement {SOCK} unix\nmanagement-client\n"
                "management-query-passwords\nmanagement-hold\n",
        "tail": f"verb 3\nkey-direction 1\n<tls-auth>\n{KEY}\n</tls-auth>\n",
    }
    parts.update(over)
    return parts["head"] + parts["mgmt"] + parts.get("extra", "") + parts["tail"]


def reject(testcase, text):
    with testcase.assertRaises(helper.HelperError):
        helper.validate_openvpn_config(text, UID)


class GoodConfig(unittest.TestCase):
    def test_generated_shape_is_accepted_and_rebuilt(self):
        out = helper.validate_openvpn_config(good_config(), UID)
        self.assertIn("remote gw.example.invalid 443", out)
        self.assertNotIn("#", out.split("<tls-auth>")[0])  # comments are dropped
        self.assertTrue(out.endswith("</tls-auth>\n"))

    def test_inline_ca_and_compat_accepted(self):
        text = good_config(extra="experimental-azure-compat\n").replace(
            "ca /etc/ssl/certs/ca-certificates.crt\n",
            "<ca>\n-----BEGIN CERTIFICATE-----\nMIIDdzCCAl+gAwIBAgIE\n-----END CERTIFICATE-----\n</ca>\n")
        helper.validate_openvpn_config(text, UID)


class DangerousDirectives(unittest.TestCase):
    def test_code_execution_directives_rejected(self):
        bad = [
            "script-security 2", "script-security 3 system", "up /tmp/x.sh", "down /tmp/x.sh",
            "up-restart", "plugin /tmp/evil.so", "route-up /tmp/x", "route-pre-down /tmp/x",
            "ipchange /tmp/x", "learn-address /tmp/x", "tls-verify /tmp/x", "client-connect /tmp/x",
            "client-disconnect /tmp/x", "auth-user-pass-verify /tmp/x via-env", "up-delay",
            "config /etc/shadow", "--config /tmp/evil.conf", "include /tmp/evil.conf",
            "management-client-user root", "management-client-group root", "setenv FOO bar",
            "setenv-safe FOO bar", "cd /", "chroot /tmp", "dh /tmp/x", "log /etc/passwd",
            "log-append /etc/passwd", "writepid /etc/cron.d/x", "daemon", "tmp-dir /tmp",
            "--up /tmp/x.sh", "--script-security 2", "ifconfig-noexec", "route-noexec",
            "key /etc/shadow", "cert /etc/shadow", "askpass /etc/shadow", "status /etc/passwd",
            "ca /etc/shadow", "ca /home/user/evil.pem", "ca ../../etc/shadow",
            "auth-user-pass /etc/shadow", f"auth-user-pass /run/user/{UID}/openp2s/credentials",
            "dev tap", "dev-node /dev/sda", "cipher none", "proto udp", "verb 99", "remote -oProxy 443",
            "remote host 99999", "remote host", "remote gw.example.invalid 443 udp",
            "pull-filter accept up", "shaper 1", "mlock", "user root", "ccd-exclusive",
            "http-proxy-user-pass /etc/shadow", "connect-retry-max 1", "tls-crypt /etc/shadow",
            "tls-auth /etc/shadow 1", "management /tmp/x.sock unix", "management 127.0.0.1 7505",
            f"management {SOCK} unix extra", f"management /run/user/{UID}/openp2s/../x unix",
            f"management /run/user/{UID + 1}/openp2s/m.sock unix",
            f"management /run/user/{UID}/openp2s/sub/m.sock unix",
        ]
        for line in bad:
            with self.subTest(line=line):
                reject(self, good_config(extra=line + "\n"))

    def test_obfuscation_tricks_rejected(self):
        tricks = [
            "up\t/tmp/x.sh",  # tab
            "client\rup /tmp/x",  # CR
            "client; up /tmp/x",  # separator
            "verb 3 # up x",
            'remote "a b" 443',
            "remote gw.example.invalid 443\\\nup /tmp/x",
            "up\x00/tmp/x",
            "up /tmp/é",
            "client `id`",
            "client $(id)",
            "  UP /tmp/x",  # wrong case still unknown directive
            "script-security\t2",
        ]
        for line in tricks:
            with self.subTest(line=line):
                reject(self, good_config(extra=line + "\n"))

    def test_unknown_or_dangerous_inline_blocks_rejected(self):
        for tag in ("cert", "key", "extra-certs", "pkcs12", "dh", "tls-crypt", "connection", "peer-fingerprint"):
            with self.subTest(tag=tag):
                reject(self, good_config(extra=f"<{tag}>\nAAAA\n</{tag}>\n"))

    def test_block_bodies_must_be_key_material(self):
        reject(self, good_config(tail="verb 3\nkey-direction 1\n<tls-auth>\nup /tmp/x.sh\n</tls-auth>\n"))
        reject(self, good_config(tail="verb 3\nkey-direction 1\n<tls-auth>\nAAAA\n"))  # unterminated
        reject(self, good_config(tail="verb 3\nkey-direction 1\n<tls-auth>\n</tls-auth>\n"))  # empty
        reject(self, good_config(tail="verb 3\nkey-direction 1\n<tls-auth>\nAAAA\n</tls-auth>\nscript-security 2\n"))

    def test_missing_required_directives_rejected(self):
        reject(self, good_config().replace("management-hold\n", ""))
        reject(self, good_config().replace("auth-user-pass\n", ""))
        reject(self, good_config().replace("remote gw.example.invalid 443\n", ""))
        reject(self, good_config().replace("ca /etc/ssl/certs/ca-certificates.crt\n", ""))
        reject(self, good_config().replace("<tls-auth>", "<ca>").replace("</tls-auth>", "</ca>"))

    def test_size_and_charset_limits(self):
        reject(self, good_config(extra="#" + "a" * 70000 + "\n"))
        reject(self, good_config(extra="# comment ‮\n"))


class ManagementSocketChecks(unittest.TestCase):
    def test_existing_symlink_socket_rejected(self):
        # lstat of a path that exists but is not a socket owned by the caller
        with tempfile.TemporaryDirectory() as td:
            real = Path(td) / "f"
            real.write_text("x")
            orig = helper.runtime_dir
            helper.runtime_dir = lambda uid: td
            try:
                with self.assertRaises(helper.HelperError):
                    helper._validate_management([str(real), "unix"], os.getuid())
            finally:
                helper.runtime_dir = orig


class FixedCommandLine(unittest.TestCase):
    def test_openvpn_argv_is_fixed(self):
        self.assertEqual(helper.build_openvpn_argv("/run/azurevpn/openvpn-1.conf"),
                         ["/usr/local/lib/openp2s/openvpn", "--config", "/run/azurevpn/openvpn-1.conf"])

    def test_main_rejects_extra_arguments_and_unknown_subcommands(self):
        import contextlib
        import io
        for argv in ([], ["connect", "--script-security", "2"], ["connect", "x"], ["bogus"],
                     ["--config", "/tmp/x"], ["dns-servers", "extra"], ["openvpn"], ["connect", "--config", "/tmp/x"]):
            with self.subTest(argv=argv):
                err = io.StringIO()
                with contextlib.redirect_stderr(err):
                    # euid=0 simulates root so the argument check itself is exercised.
                    self.assertEqual(helper.main(argv, {"SUDO_UID": "1000"}, euid=0), 2)
                self.assertIn("usage", err.getvalue())

    def test_main_refuses_when_not_root(self):
        import contextlib
        import io
        with contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(helper.main(["connect"], {"SUDO_UID": "1000"}, euid=1000), 2)

    def test_environment_is_minimal(self):
        self.assertEqual(set(helper.CLEAN_ENV), {"PATH", "LC_ALL", "LANG"})
        self.assertNotIn("LD_PRELOAD", helper.CLEAN_ENV)


class CallerIdentity(unittest.TestCase):
    def test_sudo_uid_required_and_validated(self):
        self.assertEqual(helper.caller_uid({"SUDO_UID": "1000"}), 1000)
        for bad in ({}, {"SUDO_UID": ""}, {"SUDO_UID": "0"}, {"SUDO_UID": "-1"},
                    {"SUDO_UID": "1000; id"}, {"SUDO_UID": "../0"}, {"SUDO_UID": "99999999999"},
                    {"SUDO_UID": "4294967295"}, {"SUDO_UID": "01"}):
            with self.subTest(env=bad):
                with self.assertRaises(helper.HelperError):
                    helper.caller_uid(bad)

    def test_source_config_path_is_derived_not_supplied(self):
        self.assertEqual(helper.source_config_path(1000), "/run/user/1000/openp2s/openvpn.conf")


class DnsRequests(unittest.TestCase):
    def test_valid_requests(self):
        self.assertEqual(helper.parse_dns_request("dns-servers", "tun0\n10.0.0.4\nfd00::1\n"),
                         ["dns", "tun0", "10.0.0.4", "fd00::1"])
        self.assertEqual(helper.parse_dns_request("dns-domains", "tun1\ncorp.example.invalid\n~vpn.example.invalid\n~.\n"),
                         ["domain", "tun1", "corp.example.invalid", "~vpn.example.invalid", "~."])
        self.assertEqual(helper.parse_dns_request("dns-default-route", "tun0\n"), ["default-route", "tun0", "no"])
        self.assertEqual(helper.parse_dns_request("dns-revert", "tun0\n"), ["revert", "tun0"])

    def test_bad_interfaces_rejected(self):
        for iface in ("eth0", "wlan0", "lo", "tun", "tun99999", "tun0; reboot", "-h", "../tun0",
                      "tun0 tun1", "tun0\x00", "TUN0", "tap0", "tun0/../eth0", ""):
            with self.subTest(iface=iface):
                with self.assertRaises(helper.HelperError):
                    helper.parse_dns_request("dns-revert", iface + "\n")

    def test_bad_dns_servers_rejected(self):
        for v in ("not-an-ip", "10.0.0.1 --set-dns", "-h", "10.0.0.256", "example.com",
                  "10.0.0.1/24", "1.2.3", "::g", "0x7f000001", ""):
            with self.subTest(v=v):
                with self.assertRaises(helper.HelperError):
                    helper.parse_dns_request("dns-servers", f"tun0\n{v}\n")
        with self.assertRaises(helper.HelperError):
            helper.parse_dns_request("dns-servers", "tun0\n")
        with self.assertRaises(helper.HelperError):
            helper.parse_dns_request("dns-servers", "tun0\n" + "10.0.0.1\n" * 9)

    def test_bad_domains_rejected(self):
        for v in ("-h", "--flush-caches", "a b", "a;b", "$(id)", "../x", "~", "..", "a" * 64 + ".com", "x/y"):
            with self.subTest(v=v):
                with self.assertRaises(helper.HelperError):
                    helper.parse_dns_request("dns-domains", f"tun0\n{v}\n")

    def test_extra_input_and_unknown_kinds_rejected(self):
        with self.assertRaises(helper.HelperError):
            helper.parse_dns_request("dns-revert", "tun0\nextra\n")
        with self.assertRaises(helper.HelperError):
            helper.parse_dns_request("dns-default-route", "tun0\nyes\n")
        with self.assertRaises(helper.HelperError):
            helper.parse_dns_request("status", "tun0\n")
        with self.assertRaises(helper.HelperError):
            helper.parse_dns_request("dns-revert", "")
        with self.assertRaises(helper.HelperError):
            helper.parse_dns_request("dns-servers", "tun0\n" + "x" * 9000)


class FilesystemTrust(unittest.TestCase):
    def test_root_owned_chain_rejects_user_owned_and_writable_and_symlinks(self):
        with tempfile.TemporaryDirectory() as td:
            f = Path(td) / "bin"
            f.write_text("x")
            me = os.getuid()
            # Pretend "root" is the current user so the chain can be built in a temp dir.
            if me != 0:
                with self.assertRaises(helper.HelperError):  # real root uid 0 != me
                    helper.assert_root_owned_chain(str(f))
            os.chmod(td, 0o755)
            os.chmod(f, 0o755)
            helper.assert_root_owned_chain(str(f), root_uid=me, lstat=_skip_above(td))
            os.chmod(f, 0o777)
            with self.assertRaises(helper.HelperError):
                helper.assert_root_owned_chain(str(f), root_uid=me, lstat=_skip_above(td))
            os.chmod(f, 0o755)
            link = Path(td) / "link"
            link.symlink_to(f)
            with self.assertRaises(helper.HelperError):
                helper.assert_root_owned_chain(str(link), root_uid=me, lstat=_skip_above(td))

    def test_traversal_and_relative_paths_rejected(self):
        for p in ("relative/path", "/usr/local/lib/../../../etc/shadow", "/a/../b"):
            with self.subTest(p=p):
                with self.assertRaises(helper.HelperError):
                    helper.assert_root_owned_chain(p)

    def test_read_user_config_rejects_symlink_foreign_owner_and_oversize(self):
        with tempfile.TemporaryDirectory() as td:
            real = Path(td) / "real.conf"
            real.write_text(good_config())
            me = os.getuid()
            self.assertIn("client", helper.read_user_config(me, str(real)))
            link = Path(td) / "link.conf"
            link.symlink_to(real)
            with self.assertRaises(helper.HelperError):
                helper.read_user_config(me, str(link))          # symlink
            with self.assertRaises(helper.HelperError):
                helper.read_user_config(me + 1, str(real))      # not owned by claimed caller
            big = Path(td) / "big.conf"
            big.write_text("#" * (helper.MAX_CONFIG_BYTES + 10))
            with self.assertRaises(helper.HelperError):
                helper.read_user_config(me, str(big))
            hard = Path(td) / "hard.conf"
            os.link(real, hard)
            with self.assertRaises(helper.HelperError):
                helper.read_user_config(me, str(hard))          # hard link (nlink 2)

    def test_private_config_written_0600_with_validated_content_only(self):
        with tempfile.TemporaryDirectory() as td:
            run = Path(td) / "azurevpn"
            clean = helper.validate_openvpn_config(good_config(extra="# up /tmp/x\n"), UID)
            dest = helper.write_private_config(clean, UID, run_dir=str(run))
            self.assertEqual(stat.S_IMODE(os.stat(dest).st_mode), 0o600)
            self.assertEqual(stat.S_IMODE(os.stat(run).st_mode), 0o700)
            self.assertNotIn("/tmp/x", Path(dest).read_text())
            helper.write_private_config(clean, UID, run_dir=str(run))  # overwrite is fine
            os.chmod(run, 0o755)
            with self.assertRaises(helper.HelperError):
                helper.write_private_config(clean, UID, run_dir=str(run))


def _skip_above(top):
    """lstat that reports directories above `top` as fine (root-owned stand-ins)."""
    real = os.lstat
    top = os.path.realpath(top)

    def fake(path):
        st = real(path)
        if not os.path.realpath(path).startswith(top):
            class S:  # pragma: no cover - ownership stand-in for system dirs
                st_mode = stat.S_IFDIR | 0o755
                st_uid = os.getuid()
            return S
        return st
    return fake


class SudoShim(unittest.TestCase):
    def test_translates_only_known_command_lines(self):
        self.assertEqual(shim.translate(["--", shim.OPENVPN_BIN, "--config", f"/run/user/{UID}/openp2s/openvpn.conf"], UID),
                         ("connect", ""))
        self.assertEqual(shim.translate(["--", "/usr/bin/resolvectl", "dns", "tun0", "10.0.0.4"], UID),
                         ("dns-servers", "tun0\n10.0.0.4\n"))
        self.assertEqual(shim.translate(["--", "/usr/bin/resolvectl", "default-route", "tun0", "no"], UID),
                         ("dns-default-route", "tun0\n"))
        self.assertEqual(shim.translate(["--", "/usr/bin/resolvectl", "revert", "tun0"], UID), ("dns-revert", "tun0\n"))

    def test_refuses_everything_else(self):
        bad = [
            ["--", shim.OPENVPN_BIN, "--config", "/tmp/evil.conf"],
            ["--", shim.OPENVPN_BIN, "--script-security", "2", "--up", "/tmp/x"],
            ["--", shim.OPENVPN_BIN, "--config", f"/run/user/{UID}/openp2s/openvpn.conf", "--up", "/x"],
            ["--", "/bin/sh", "-c", "id"], ["--", "id"], [], ["--"],
            ["--", "/usr/bin/resolvectl", "default-route", "tun0", "yes"],
            ["--", "/usr/bin/resolvectl", "dns"], ["--", "/usr/bin/resolvectl", "flush-caches"],
        ]
        for argv in bad:
            with self.subTest(argv=argv):
                with self.assertRaises(ValueError):
                    shim.translate(argv, UID)


if __name__ == "__main__":
    unittest.main()
